Feature/select
Braun-Johannes/Capstone-Project-BattlePets pull request #15
Opened 2024-05-28 14:31 UTC by FelixNeumayr

2024-05-28 15:20 UTC, evabergold requested changes

2024-05-28 15:20 UTC, evabergold commented on pages/index.js
Maybe it's just me, but I don't understand why the `CurrentPet`component is rendered on the homepage and not on a separate details/Living Room page on which you are routed when you select the pet. Also, there is no other way to get back to the pets overview than a page reload, right?

2024-05-28 15:20 UTC, evabergold commented on components/PetForm.jsx
More for QA, but if you click into the "name" field of the form, I get a dropdown menu from which I can also select a pet. After selecting one of these, I can not click on another pet from the pet list on the page (the selected pet does not change). 

<img width="571" alt="image" src="https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/163883411/5cf6b023-d7a2-4257-9bc8-ca194adc7f8e">

2024-05-28 15:35 UTC, Jonstar22 commented on pages/index.js
This is intentional: everything is managed through a single page because only one pet can be played with at a time. This means that as long as a pet exists, the option to select another one should not be available.

2024-05-28 15:37 UTC, Jonstar22 commented on components/PetForm.jsx
This is strange; there shouldn't be a drop-down menu.

However, it's intentional that if you choose a name before selecting a pet, the chosen name should remain. So, if you accidentally enter the name of an existing pet and then select a different pet, the entered name will still be preserved.

2024-05-29 09:44 UTC, evabergold approved these changes
looks good to me now! :-)

2024-05-29 09:44 UTC, evabergold commented on components/PetForm.jsx
looks good now!

2024-05-29 09:56 UTC, merged