Styling/icons
Braun-Johannes/Capstone-Project-BattlePets pull request #31
Opened 2024-06-06 15:08 UTC by Braun-Johannes

2024-06-07 06:41 UTC, doemser commented on utils/index.js
> +export function SVGIcon({ variant, color = "black", size = 50, ariaLabel }) {
this is not a utils function, it is a react function component and should be treated as it

2024-06-07 06:42 UTC, doemser commented on components/CurrentPet.jsx
> +        <SVGIcon variant={selectedPet.type} size={300} />
Probably better to call props names starting with "$" else you are passing useless attributes to the dom

2024-06-07 06:43 UTC, doemser requested changes
Good one, but place the icon component in the components folder

2024-06-07 07:45 UTC, doemser approved these changes

2024-06-07 07:45 UTC, doemser commented on components/PetList.jsx
> +                <SVGIcon $variant={pet.type} size={100} ariaLabel={pet.type} />
I am sorry I left the comment for the prop name prefixes with "$" which only applies to styled components. As you are not even using styled components on the SVGIcon.. it is safe to say, that I was completely wrong :D

2024-06-10 07:30 UTC, evabergold approved these changes

2024-06-10 09:04 UTC, merged